name: Generate-SourceCred

on:
  schedule:
    # Daily at 8am
    - cron: 0 8 * * *

jobs:
  GenerateSourcecred:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1
    - name: Build the Docker image
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        SOURCECRED_GITHUB_TOKEN=${TOKEN} docker run -i -v sourcecred_data:/data -e SOURCECRED_GITHUB_TOKEN sourcecred/sourcecred:ignore-token-regex load ${GITHUB_REPOSITORY}
        SOURCECRED_GITHUB_TOKEN=${TOKEN} docker run -i -v sourcecred_data:/data sourcecred/sourcecred:ignore-token-regex scores ${GITHUB_REPOSITORY} > scores.json
        SOURCECRED_GITHUB_TOKEN=${TOKEN} docker run -i -e SOURCECRED_GITHUB_TOKEN sourcecred/widgets < scores.json > contributors.svg
    - name: Checkout New Branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "GitHub Actor: ${GITHUB_ACTOR}"
        git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git branch
        git checkout -b update/sourcecred-$(date '+%Y-%m-%d')
        git branch

        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"

        git add contributors.svg
        git commit -m "Automated deployment to update contributors.svg $(date '+%Y-%m-%d')" --allow-empty
        git push origin update/sourcecred-$(date '+%Y-%m-%d')
    - name: Open pull request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH_AGAINST: "master"
      run: |
          export BRANCH_FROM="update/sourcecred-$(date '+%Y-%m-%d')"
          wget https://gist.githubusercontent.com/vsoch/074f4895e52f7fa0574a3a7a51d5c9d8/raw/ddfedf86abd2b78332b955325d5d93f37d1353b4/pull_request.sh
          chmod +x pull_request.sh
          /bin/bash pull_request.sh
